/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const SchoolID = IDL.Nat;
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const StudentID = IDL.Nat;
export const FeeID = IDL.Nat;
export const FeeAssignmentID = IDL.Nat;
export const ClassID = IDL.Nat;
export const SessionID = IDL.Nat;
export const FeeHead = IDL.Variant({
  'Library' : IDL.Null,
  'Admission' : IDL.Null,
  'Exam' : IDL.Null,
  'Tuition' : IDL.Null,
  'Other' : IDL.Text,
  'Hostel' : IDL.Null,
});
export const StaffID = IDL.Nat;
export const UserRole = IDL.Variant({
  'accountant' : IDL.Null,
  'librarian' : IDL.Null,
  'admin' : IDL.Null,
  'teacher' : IDL.Null,
  'student' : IDL.Null,
  'superadmin' : IDL.Null,
  'parent' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'studentId' : IDL.Opt(StudentID),
  'staffId' : IDL.Opt(StaffID),
  'name' : IDL.Text,
  'role' : UserRole,
  'schoolId' : IDL.Opt(SchoolID),
  'childrenIds' : IDL.Vec(StudentID),
});
export const FeeMaster = IDL.Record({
  'id' : FeeID,
  'feeHead' : FeeHead,
  'dueDate' : IDL.Int,
  'classId' : ClassID,
  'schoolId' : SchoolID,
  'sessionId' : SessionID,
  'amount' : IDL.Float64,
});
export const FinancialSummary = IDL.Record({
  'defaultersCount' : IDL.Nat,
  'totalCollected' : IDL.Float64,
  'totalPending' : IDL.Float64,
});
export const School = IDL.Record({
  'id' : SchoolID,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const PaymentID = IDL.Nat;
export const PaymentMode = IDL.Variant({
  'Cash' : IDL.Null,
  'Online' : IDL.Null,
  'BankTransfer' : IDL.Null,
  'Cheque' : IDL.Null,
});
export const FeePayment = IDL.Record({
  'id' : PaymentID,
  'feeAssignmentId' : FeeAssignmentID,
  'studentId' : StudentID,
  'receiptNum' : IDL.Text,
  'recordedBy' : IDL.Principal,
  'amountPaid' : IDL.Float64,
  'schoolId' : SchoolID,
  'paymentDate' : IDL.Int,
  'paymentMode' : PaymentMode,
});
export const FeeAssignment = IDL.Record({
  'id' : FeeAssignmentID,
  'studentId' : StudentID,
  'assignedAt' : IDL.Int,
  'assignedBy' : IDL.Principal,
  'schoolId' : SchoolID,
  'feeId' : FeeID,
});
export const FeeLedgerEntry = IDL.Record({
  'payments' : IDL.Vec(FeePayment),
  'outstanding' : IDL.Float64,
  'totalPaid' : IDL.Float64,
  'feeAssignment' : FeeAssignment,
  'feeMaster' : FeeMaster,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addSchool' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [SchoolID],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'assignFeeToStudent' : IDL.Func([StudentID, FeeID], [FeeAssignmentID], []),
  'createFeeMaster' : IDL.Func(
      [SchoolID, ClassID, SessionID, FeeHead, IDL.Float64, IDL.Int],
      [FeeID],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getFeeDefaulters' : IDL.Func(
      [SchoolID, IDL.Opt(ClassID), IDL.Opt(SessionID)],
      [IDL.Vec(StudentID)],
      ['query'],
    ),
  'getFeeMasters' : IDL.Func([SchoolID], [IDL.Vec(FeeMaster)], ['query']),
  'getFinancialSummary' : IDL.Func(
      [SchoolID, IDL.Opt(IDL.Int), IDL.Opt(IDL.Int)],
      [FinancialSummary],
      ['query'],
    ),
  'getRemoteSchools' : IDL.Func([], [IDL.Vec(School)], ['query']),
  'getStudentFeeLedger' : IDL.Func(
      [StudentID],
      [IDL.Vec(FeeLedgerEntry)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordPayment' : IDL.Func(
      [StudentID, FeeAssignmentID, IDL.Float64, PaymentMode],
      [PaymentID],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchSchools' : IDL.Func([IDL.Text], [IDL.Vec(School)], ['query']),
  'updateFeeMaster' : IDL.Func([FeeID, IDL.Float64, IDL.Int], [], []),
  'updateSchool' : IDL.Func(
      [SchoolID, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const SchoolID = IDL.Nat;
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const StudentID = IDL.Nat;
  const FeeID = IDL.Nat;
  const FeeAssignmentID = IDL.Nat;
  const ClassID = IDL.Nat;
  const SessionID = IDL.Nat;
  const FeeHead = IDL.Variant({
    'Library' : IDL.Null,
    'Admission' : IDL.Null,
    'Exam' : IDL.Null,
    'Tuition' : IDL.Null,
    'Other' : IDL.Text,
    'Hostel' : IDL.Null,
  });
  const StaffID = IDL.Nat;
  const UserRole = IDL.Variant({
    'accountant' : IDL.Null,
    'librarian' : IDL.Null,
    'admin' : IDL.Null,
    'teacher' : IDL.Null,
    'student' : IDL.Null,
    'superadmin' : IDL.Null,
    'parent' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'studentId' : IDL.Opt(StudentID),
    'staffId' : IDL.Opt(StaffID),
    'name' : IDL.Text,
    'role' : UserRole,
    'schoolId' : IDL.Opt(SchoolID),
    'childrenIds' : IDL.Vec(StudentID),
  });
  const FeeMaster = IDL.Record({
    'id' : FeeID,
    'feeHead' : FeeHead,
    'dueDate' : IDL.Int,
    'classId' : ClassID,
    'schoolId' : SchoolID,
    'sessionId' : SessionID,
    'amount' : IDL.Float64,
  });
  const FinancialSummary = IDL.Record({
    'defaultersCount' : IDL.Nat,
    'totalCollected' : IDL.Float64,
    'totalPending' : IDL.Float64,
  });
  const School = IDL.Record({
    'id' : SchoolID,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const PaymentID = IDL.Nat;
  const PaymentMode = IDL.Variant({
    'Cash' : IDL.Null,
    'Online' : IDL.Null,
    'BankTransfer' : IDL.Null,
    'Cheque' : IDL.Null,
  });
  const FeePayment = IDL.Record({
    'id' : PaymentID,
    'feeAssignmentId' : FeeAssignmentID,
    'studentId' : StudentID,
    'receiptNum' : IDL.Text,
    'recordedBy' : IDL.Principal,
    'amountPaid' : IDL.Float64,
    'schoolId' : SchoolID,
    'paymentDate' : IDL.Int,
    'paymentMode' : PaymentMode,
  });
  const FeeAssignment = IDL.Record({
    'id' : FeeAssignmentID,
    'studentId' : StudentID,
    'assignedAt' : IDL.Int,
    'assignedBy' : IDL.Principal,
    'schoolId' : SchoolID,
    'feeId' : FeeID,
  });
  const FeeLedgerEntry = IDL.Record({
    'payments' : IDL.Vec(FeePayment),
    'outstanding' : IDL.Float64,
    'totalPaid' : IDL.Float64,
    'feeAssignment' : FeeAssignment,
    'feeMaster' : FeeMaster,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addSchool' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [SchoolID],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'assignFeeToStudent' : IDL.Func([StudentID, FeeID], [FeeAssignmentID], []),
    'createFeeMaster' : IDL.Func(
        [SchoolID, ClassID, SessionID, FeeHead, IDL.Float64, IDL.Int],
        [FeeID],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getFeeDefaulters' : IDL.Func(
        [SchoolID, IDL.Opt(ClassID), IDL.Opt(SessionID)],
        [IDL.Vec(StudentID)],
        ['query'],
      ),
    'getFeeMasters' : IDL.Func([SchoolID], [IDL.Vec(FeeMaster)], ['query']),
    'getFinancialSummary' : IDL.Func(
        [SchoolID, IDL.Opt(IDL.Int), IDL.Opt(IDL.Int)],
        [FinancialSummary],
        ['query'],
      ),
    'getRemoteSchools' : IDL.Func([], [IDL.Vec(School)], ['query']),
    'getStudentFeeLedger' : IDL.Func(
        [StudentID],
        [IDL.Vec(FeeLedgerEntry)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordPayment' : IDL.Func(
        [StudentID, FeeAssignmentID, IDL.Float64, PaymentMode],
        [PaymentID],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchSchools' : IDL.Func([IDL.Text], [IDL.Vec(School)], ['query']),
    'updateFeeMaster' : IDL.Func([FeeID, IDL.Float64, IDL.Int], [], []),
    'updateSchool' : IDL.Func(
        [SchoolID, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };